[colors]
foreground = "#ffffff"
background = "#101010"

cursor_bg = "#efefef"
cursor_fg = "#000000"
cursor_border = "#efefef"

ansi = [
  "#121212", 
  "#ff7676", 
  "#a3d6a3", 
  "#ffffff", 
  "#b3b3b3", 
  "#f4b8e4", 
  "#fafafa", 
  "#a5adce", 
]

brights = [
  "#666666", 
  "#ff5733", 
  "#8ec772", 
  "#d9ba73", 
  "#ffffff", 
  "#f2a4db", 
  "#5abfb5", 
  "#b5bfe2", 
]
