[colors]
background = "#fAf9F5"
foreground = "#3a3a3a"

cursor_bg = "#6a6a6a"
cursor_fg = "#f1f1f1"
cursor_border = "#6a6a6a"

selection_bg = "#3a3a3a"
selection_fg = "#f1f1f1"

ansi = [
  "#e2e2e2", 
  "#ca0043", 
  "#407f00", 
  "#926200", 
  "#006acf", 
  "#a200d1", 
  "#007d7d", 
  "#6a6a6a", 
]

brights = [
  "#ababab", 
  "#f30052", 
  "#4f9a00", 
  "#b07700", 
  "#0081f8", 
  "#c301fb", 
  "#009797", 
  "#222222", 
]
